// src/config/menuConfig.jsx

import React from "react";
import {
  Home,
  Users,
  BookOpen,
  ClipboardCheck,
  Star,
  Library,
  UserCircle,
  UserCog2,
  SquareUser,
  ChartPie,
  ChartGantt,
  ChartLine,
  ChartNetwork,
  Hourglass,
  Percent,
  ChartColumnBig,
  FilePen,
  BookOpenCheck,
  FlaskConical,
  ArrowUpWideNarrow,
  BadgePercent,
  MessageCircle,
  Video,
  MailOpen,
  GraduationCap,
  DollarSign,
  Briefcase,
  ShoppingBag,
  LetterText,
  Presentation,
  Film,
  Fullscreen,
  Baby,
  Bus,
  Hotel,
  BadgeCent,
  Mic,
  Inbox,
  Volume,
  ClipboardMinus,
  EthernetPort,
  PersonStanding,
  LockIcon,
  House,
  Settings,
  FileQuestion,
  ArrowBigUp,
  Barcode,
  QrCode,
  Bot,
  InfoIcon,
  StickyNote,
  Calculator,
  Clock,
  SquareChartGantt,
  Banknote,
  Repeat2,
  HouseIcon,
  LocateIcon,
  Store,
  Videotape,
  CassetteTape,
  Plug,
  ShoppingCart,
  TypeIcon,
  ClipboardType,
  Speaker,
  Warehouse,
  Container,
  ShoppingBasket,
  BadgePoundSterling,
  ChartCandlestick,
  AudioLines,
  FileUser,
  MailQuestion,
  VideoIcon,
  Keyboard,
  Accessibility,
  Activity,
  Zap,
} from "lucide-react";

const createMenuConfig = () => {
  return [
    {
      id: "dashboard",
      icon: <Home className="w-5 h-5" />,
      label: "Dashboard",
      path: "/",
    },
    {
      id: "students",
      icon: <Users className="w-5 h-5" />,
      label: "Students",
      path: "/students",
    },
    {
      id: "teachers",
      icon: <SquareUser className="w-5 h-5" />,
      label: "Teachers",
      path: "/teachers",
    },
    {
      id: "parents",
      icon: <UserCircle className="w-5 h-5" />,
      label: "Parents",
      path: "/parents",
    },
    {
      id: "users",
      icon: <UserCog2 className="w-5 h-5" />,
      label: "Users",
      path: "/users",
    },
    {
      id: "academic",
      icon: <BookOpen className="w-5 h-5" />,
      label: "Academic",
      subMenus: [
        {
          id: "classes",
          label: "Classes",
          path: "/academic/classes",
          icon: <ClipboardCheck className="w-4 h-4" />,
        },
        {
          id: "sections",
          label: "Sections",
          path: "/academic/sections",
          icon: <Star className="w-4 h-4" />,
        },
        {
          id: "subjects",
          label: "Subjects",
          path: "/academic/subjects",
          icon: <Library className="w-4 h-4" />,
        },
        {
          id: "syllabuses",
          label: "Syllabus",
          path: "/academic/syllabuses",
          icon: <BookOpen className="w-4 h-4" />,
        },
        {
          id: "assignments",
          label: "Assignments",
          path: "/academic/assignments",
          icon: <ClipboardCheck className="w-4 h-4" />,
        },
        {
          id: "routines",
          label: "Routines",
          path: "/academic/routines",
          icon: <ChartPie className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "attendance",
      icon: <ClipboardCheck className="w-5 h-5" />,
      label: "Attendance",
      path: "/attendance",
      subMenus: [
        {
          id: "studentAttendance",
          label: "Student Attendance",
          path: "/attendance/studentatndnc",
          icon: <ChartGantt className="w-4 h-4" />,
        },
        {
          id: "teachetAttendance",
          label: "Teacher Attendance",
          path: "/attendance/teacheratndnc",
          icon: <ChartLine className="w-4 h-4" />,
        },
        {
          id: "userAttendance",
          label: "User Attendance",
          path: "/attendance/useratndnc",
          icon: <ChartNetwork className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "exam",
      icon: <Hourglass className="w-5 h-5" />,
      label: "Exam",
      path: "/exam",
      subMenus: [
        {
          id: "exams",
          label: "Exam",
          path: "/exam/exams",
          icon: <FilePen className="w-4 h-4" />,
        },
        {
          id: "examSchedule",
          label: "Exam Schedule",
          path: "/exam/schedule",
          icon: <ChartLine className="w-4 h-4" />,
        },
        {
          id: "grade",
          label: "Grade",
          path: "/exam/grade",
          icon: <Percent className="w-4 h-4" />,
        },
        {
          id: "examAttendance",
          label: "Exam Attendance",
          path: "/exam/attendance",
          icon: <ChartColumnBig className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "mark",
      icon: <BookOpenCheck className="w-5 h-5" />,
      label: "mark",
      path: "/mark",
      subMenus: [
        {
          id: "markings",
          label: "Mark",
          path: "/mark/markings",
          icon: <FlaskConical className="w-4 h-4" />,
        },
        {
          id: "markDistribution",
          label: "Mark Distribution",
          path: "/mark/distribution",
          icon: <BadgePercent className="w-4 h-4" />,
        },
        {
          id: "promotion",
          label: "Promotion",
          path: "/mark/promotion",
          icon: <ArrowUpWideNarrow className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "message",
      icon: <MessageCircle className="w-5 h-5" />,
      label: "Message",
      path: "/message",
    },
    {
      id: "media",
      icon: <Video className="w-5 h-5" />,
      label: "Media",
      path: "/media",
    },
    {
      id: "mail",
      icon: <MailOpen className="w-5 h-5" />,
      label: "Mail/SMS",
      path: "/mail",
    },
    {
      id: "onlineExam",
      icon: <GraduationCap className="w-5 h-5" />,
      label: "Online Exam",
      path: "/onlineexam",
      subMenus: [
        {
          id: "questionGroup",
          label: "Question Group",
          path: "/onlineexam/questiongroup",
          icon: <FileQuestion className="w-4 h-4" />,
        },
        {
          id: "questionlevel",
          label: "Question Level",
          path: "/onlineexam/questionlevel",
          icon: <ArrowBigUp className="w-4 h-4" />,
        },
        {
          id: "questionBank",
          label: "Question Bank",
          path: "/onlineexam/questionbank",
          icon: <QrCode className="w-4 h-4" />,
        },
        {
          id: "onlineexams",
          label: "Online Exams",
          path: "/onlineexam/onlineexams",
          icon: <Bot className="w-4 h-4" />,
        },
        {
          id: "instructions",
          label: "Instructions",
          path: "/onlineexam/instructions",
          icon: <InfoIcon className="w-4 h-4" />,
        },
        {
          id: "takeExam",
          label: "Take Exam",
          path: "/onlineexam/takeexam",
          icon: <StickyNote className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "payroll",
      icon: <DollarSign className="w-5 h-5" />,
      label: "Payroll",
      path: "/payroll",
      subMenus: [
        {
          id: "salarytemplate",
          label: "Salary Template",
          path: "/payroll/salarytemplate",
          icon: <Calculator className="w-4 h-4" />,
        },
        {
          id: "hourlytemplate",
          label: "Hourly Template",
          path: "/payroll/hourlytemplate",
          icon: <Clock className="w-4 h-4" />,
        },
        {
          id: "managesalary",
          label: "Manage Salary",
          path: "/payroll/managesalary",
          icon: <SquareChartGantt className="w-4 h-4" />,
        },
        {
          id: "makePayment",
          label: "Make Payment",
          path: "/payroll/makepayment",
          icon: <Banknote className="w-4 h-4" />,
        },
        {
          id: "overTime",
          label: "Over Time",
          path: "/payroll/overtime",
          icon: <Repeat2 className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "assetManagement",
      icon: <Briefcase className="w-5 h-5" />,
      label: "Asset Management",
      path: "/assetmanagement",
      subMenus: [
        {
          id: "vendor",
          label: "Vendor",
          path: "/assetmanagement/vendor",
          icon: <Store className="w-4 h-4" />,
        },
        {
          id: "location",
          label: "Location",
          path: "/assetmanagement/location",
          icon: <LocateIcon className="w-4 h-4" />,
        },
        {
          id: "assetCategory",
          label: "Asset Category",
          path: "/assetmanagement/assetcategory",
          icon: <Videotape className="w-4 h-4" />,
        },
        {
          id: "asset",
          label: "Asset",
          path: "/assetmanagement/asset",
          icon: <CassetteTape className="w-4 h-4" />,
        },
        {
          id: "assetassignment",
          label: "Asset Assignment",
          path: "/assetmanagement/assetassignment",
          icon: <Plug className="w-4 h-4" />,
        },
        {
          id: "purchase",
          label: "Purchase",
          path: "/assetmanagement/purchase",
          icon: <ShoppingCart className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "inventory",
      icon: <ShoppingBag className="w-5 h-5" />,
      label: "Inventory",
      path: "/inventory",
      subMenus: [
        {
          id: "category",
          label: "Category",
          path: "/inventory/category",
          icon: <ClipboardType className="w-4 h-4" />,
        },
        {
          id: "product",
          label: "Product",
          path: "/inventory/product",
          icon: <Speaker className="w-4 h-4" />,
        },
        {
          id: "warehouse",
          label: "Warehouse",
          path: "/inventory/warehouse",
          icon: <Warehouse className="w-4 h-4" />,
        },
        {
          id: "supplier",
          label: "Supplier",
          path: "/inventory/supplier",
          icon: <Container className="w-4 h-4" />,
        },
        {
          id: "purchase",
          label: "Purchase",
          path: "/inventory/purchase",
          icon: <ShoppingBasket className="w-4 h-4" />,
        },
        {
          id: "sale",
          label: "Sale",
          path: "/inventory/sale",
          icon: <BadgePoundSterling className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "leaveApplication",
      icon: <LetterText className="w-5 h-5" />,
      label: "Leave Application",
      path: "/leaveappication",
      subMenus: [
        {
          id: "leaveCategory",
          label: "Leave Category",
          path: "/leaveapplication/leavecategory",
          icon: <ChartCandlestick className="w-4 h-4" />,
        },
        {
          id: "leaveassign",
          label: "Leave Assign",
          path: "/leaveapplication/leaveassign",
          icon: <AudioLines className="w-4 h-4" />,
        },
        {
          id: "leaveApply",
          label: "Leave Apply",
          path: "/leaveapplication/leaveapply",
          icon: <FileUser className="w-4 h-4" />,
        },
        {
          id: "leaveapplications",
          label: "Leave Applications",
          path: "/leaveapplication/leaveapplications",
          icon: <MailQuestion className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "googleMeetClass",
      icon: <Presentation className="w-5 h-5" />,
      label: "Google Meet Class",
      path: "/googlemeetclass",
    },
    {
      id: "tutorial",
      icon: <Film className="w-5 h-5" />,
      label: "Tutorial",
      path: "/tutorial",
    },
    {
      id: "zoomMeeting",
      icon: <Fullscreen className="w-5 h-5" />,
      label: "Zoom Meeting",
      path: "/zoommeeting",
      subMenus: [
        {
          id: "liveclass",
          label: "Live Class",
          path: "/zoommeeting/liveclass",
          icon: <VideoIcon className="w-4 h-4" />,
        },
        {
          id: "zoomsettings",
          label: "Zoom Settings",
          path: "/zoommeeting/zoomsettings",
          icon: <Keyboard className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "child",
      icon: <Baby className="w-5 h-5" />,
      label: "Child",
      path: "/child",
      subMenus: [
        {
          id: "activitiescategory",
          label: "Activity Category",
          path: "/child/activitiescategory",
          icon: <Zap className="w-4 h-4" />,
        },
        {
          id: "activities",
          label: "Activiti",
          path: "/child/activities",
          icon: <Activity className="w-4 h-4" />,
        },
        {
          id: "childcare",
          label: "Child Care",
          path: "/child/childcare",
          icon: <Accessibility className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "library",
      icon: <Library className="w-5 h-5" />,
      label: "Library",
      path: "/library",
      subMenus: [
        {
          id: "liveclass",
          label: "Live Class",
          path: "/zoommeeting/liveclass",
          icon: <VideoIcon className="w-4 h-4" />,
        },
        {
          id: "zoomsettings",
          label: "Zoom Settings",
          path: "/zoommeeting/zoomsettings",
          icon: <Keyboard className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "transport",
      icon: <Bus className="w-5 h-5" />,
      label: "Transport",
      path: "/transport",
    },
    {
      id: "hotel",
      icon: <Hotel className="w-5 h-5" />,
      label: "Hotel",
      path: "/hotel",
    },
    {
      id: "sponsorship",
      icon: <BadgeCent className="w-5 h-5" />,
      label: "Sponsorship",
      path: "/sponsorship",
    },
    {
      id: "account",
      icon: <Inbox className="w-5 h-5" />,
      label: "Account",
      path: "/account",
    },
    {
      id: "announcement",
      icon: <Volume className="w-5 h-5" />,
      label: "Announcement",
      path: "/announcement",
    },
    {
      id: "report",
      icon: <ClipboardMinus className="w-5 h-5" />,
      label: "Report",
      path: "/report",
    },
    {
      id: "onlineAdmission",
      icon: <EthernetPort className="w-5 h-5" />,
      label: "Online Admission",
      path: "/onlineadmission",
    },
    {
      id: "visitorInformation",
      icon: <PersonStanding className="w-5 h-5" />,
      label: "Visitor Information",
      path: "/visitorinformation",
    },
    {
      id: "administrator",
      icon: <LockIcon className="w-5 h-5" />,
      label: "Administrator",
      path: "/administrator",
    },
    {
      id: "frontend",
      icon: <House className="w-5 h-5" />,
      label: "Frontend",
      path: "/frontend",
    },
    {
      id: "settings",
      icon: <Settings className="w-5 h-5" />,
      label: "Settings",
      path: "/settings",
    },
  ];
};

export const menuItems = createMenuConfig();
