// src/config/menuConfig.jsx

import React from "react";
import {
  Accessibility,
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowBigUp,
  ArrowLeftRight,
  ArrowUpWideNarrow,
  AudioLines,
  Award,
  Baby,
  BadgeCent,
  BadgePercent,
  BadgePoundSterling,
  Banknote,
  Barcode,
  BookA,
  BookCheck,
  BookOpen,
  BookOpenCheck,
  BookOpenCheckIcon,
  BookText,
  Bot,
  Briefcase,
  Bus,
  BusFrontIcon,
  Calculator,
  CalendarClock,
  CalendarX,
  CarrotIcon,
  CassetteTape,
  ChartCandlestick,
  ChartColumnBig,
  ChartGantt,
  ChartLine,
  ChartNetwork,
  ChartPie,
  Clock,
  ClipboardCheck,
  ClipboardList,
  ClipboardMinus,
  ClipboardType,
  Container,
  DollarSign,
  EthernetPort,
  FileQuestion,
  FilePen,
  FileSpreadsheet,
  FileUser,
  Film,
  FlaskConical,
  Fullscreen,
  Globe,
  GraduationCap,
  History,
  Home,
  Hotel,
  Hourglass,
  House,
  HouseIcon,
  HousePlug,
  IdCard,
  InfoIcon,
  Inbox,
  Keyboard,
  Leaf,
  LetterText,
  Library,
  ListChecks,
  LocateIcon,
  LockIcon,
  MailOpen,
  MailQuestion,
  MessageCircle,
  MessageSquareCode,
  Mic,
  MonitorPlay,
  Percent,
  PersonStanding,
  PersonStandingIcon,
  Plug,
  Presentation,
  QrCode,
  Receipt,
  Repeat2,
  Route,
  Scale as ScaleIcon,
  School,
  Search,
  Settings,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Speaker,
  SquareChartGantt,
  SquareUser,
  Star,
  StickyNote,
  Store,
  Table,
  Terminal,
  Ticket,
  TrendingDown,
  TrendingUp,
  TypeIcon,
  User2Icon,
  UserCircle,
  UserCog2,
  UserPlus,
  Users,
  UserSquare,
  Video,
  VideoIcon,
  Videotape,
  Volume,
  Wallet,
  Warehouse,
  Zap,
  Clock1,
  FileCheck,
  NotebookIcon,
  Projector,
  Umbrella,
  Calendar,
  UserCog,
  PlusCircle,
  FileText,
  Key,
  Link,
  Mail,
  Download,
  Save,
  Shield,
  RefreshCw,
  FolderTree,
  Files,
  MenuSquare,
  Settings2,
  LayoutTemplate,
  CreditCard,
  MessageSquare,
  CheckSquare,
} from "lucide-react";

const createMenuConfig = () => {
  return [
    {
      id: "dashboard",
      icon: <Home className="w-5 h-5" />,
      label: "Dashboard",
      path: "/admin/dashboard",
    },
    {
      id: "students",
      icon: <Users className="w-5 h-5" />,
      label: "Students",
      path: "/students",
    },
    {
      id: "teachers",
      icon: <SquareUser className="w-5 h-5" />,
      label: "Teachers",
      path: "/teachers",
    },
    {
      id: "parents",
      icon: <UserCircle className="w-5 h-5" />,
      label: "Parents",
      path: "/parents",
    },
    {
      id: "users",
      icon: <UserCog2 className="w-5 h-5" />,
      label: "Users",
      path: "/users",
    },
    {
      id: "academic",
      icon: <BookOpen className="w-5 h-5" />,
      label: "Academic",
      subMenus: [
        {
          id: "classes",
          label: "Classes",
          path: "/academic/classes",
          icon: <ClipboardCheck className="w-4 h-4" />,
        },
        {
          id: "sections",
          label: "Sections",
          path: "/academic/sections",
          icon: <Star className="w-4 h-4" />,
        },
        {
          id: "subjects",
          label: "Subjects",
          path: "/academic/subjects",
          icon: <Library className="w-4 h-4" />,
        },
        {
          id: "syllabuses",
          label: "Syllabus",
          path: "/academic/syllabuses",
          icon: <BookOpen className="w-4 h-4" />,
        },
        {
          id: "assignments",
          label: "Assignments",
          path: "/academic/assignments",
          icon: <ClipboardCheck className="w-4 h-4" />,
        },
        {
          id: "routines",
          label: "Routines",
          path: "/academic/routines",
          icon: <ChartPie className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "attendance",
      icon: <ClipboardCheck className="w-5 h-5" />,
      label: "Attendance",
      path: "/attendance",
      subMenus: [
        {
          id: "studentAttendance",
          label: "Student Attendance",
          path: "/attendance/studentatndnc",
          icon: <ChartGantt className="w-4 h-4" />,
        },
        {
          id: "teachetAttendance",
          label: "Teacher Attendance",
          path: "/attendance/teacheratndnc",
          icon: <ChartLine className="w-4 h-4" />,
        },
        {
          id: "userAttendance",
          label: "User Attendance",
          path: "/attendance/useratndnc",
          icon: <ChartNetwork className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "exam",
      icon: <Hourglass className="w-5 h-5" />,
      label: "Exam",
      path: "/exam",
      subMenus: [
        {
          id: "exams",
          label: "Exam",
          path: "/exam/exams",
          icon: <FilePen className="w-4 h-4" />,
        },
        {
          id: "examSchedule",
          label: "Exam Schedule",
          path: "/exam/schedule",
          icon: <ChartLine className="w-4 h-4" />,
        },
        {
          id: "grade",
          label: "Grade",
          path: "/exam/grade",
          icon: <Percent className="w-4 h-4" />,
        },
        {
          id: "examAttendance",
          label: "Exam Attendance",
          path: "/exam/attendance",
          icon: <ChartColumnBig className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "mark",
      icon: <BookOpenCheck className="w-5 h-5" />,
      label: "Mark",
      path: "/mark",
      subMenus: [
        {
          id: "markings",
          label: "Mark",
          path: "/mark/markings",
          icon: <FlaskConical className="w-4 h-4" />,
        },
        {
          id: "markDistribution",
          label: "Mark Distribution",
          path: "/mark/distribution",
          icon: <BadgePercent className="w-4 h-4" />,
        },
        {
          id: "promotion",
          label: "Promotion",
          path: "/mark/promotion",
          icon: <ArrowUpWideNarrow className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "message",
      icon: <MessageCircle className="w-5 h-5" />,
      label: "Message",
      path: "/message",
    },
    {
      id: "media",
      icon: <Video className="w-5 h-5" />,
      label: "Media",
      path: "/media",
    },
    {
      id: "mail",
      icon: <MailOpen className="w-5 h-5" />,
      label: "Mail/SMS",
      path: "/mail",
    },
    {
      id: "onlineExam",
      icon: <GraduationCap className="w-5 h-5" />,
      label: "Online Exam",
      path: "/onlineexam",
      subMenus: [
        {
          id: "questionGroup",
          label: "Question Group",
          path: "/onlineexam/questiongroup",
          icon: <FileQuestion className="w-4 h-4" />,
        },
        {
          id: "questionlevel",
          label: "Question Level",
          path: "/onlineexam/questionlevel",
          icon: <ArrowBigUp className="w-4 h-4" />,
        },
        {
          id: "questionBank",
          label: "Question Bank",
          path: "/onlineexam/questionbank",
          icon: <QrCode className="w-4 h-4" />,
        },
        {
          id: "onlineexams",
          label: "Online Exams",
          path: "/onlineexam/onlineexams",
          icon: <Bot className="w-4 h-4" />,
        },
        {
          id: "instructions",
          label: "Instructions",
          path: "/onlineexam/instructions",
          icon: <InfoIcon className="w-4 h-4" />,
        },
        {
          id: "takeExam",
          label: "Take Exam",
          path: "/onlineexam/takeexam",
          icon: <StickyNote className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "payroll",
      icon: <DollarSign className="w-5 h-5" />,
      label: "Payroll",
      path: "/payroll",
      subMenus: [
        {
          id: "salarytemplate",
          label: "Salary Template",
          path: "/payroll/salarytemplate",
          icon: <Calculator className="w-4 h-4" />,
        },
        {
          id: "hourlytemplate",
          label: "Hourly Template",
          path: "/payroll/hourlytemplate",
          icon: <Clock className="w-4 h-4" />,
        },
        {
          id: "managesalary",
          label: "Manage Salary",
          path: "/payroll/managesalary",
          icon: <SquareChartGantt className="w-4 h-4" />,
        },
        {
          id: "makePayment",
          label: "Make Payment",
          path: "/payroll/makepayment",
          icon: <Banknote className="w-4 h-4" />,
        },
        {
          id: "overTime",
          label: "Over Time",
          path: "/payroll/overtime",
          icon: <Repeat2 className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "assetManagement",
      icon: <Briefcase className="w-5 h-5" />,
      label: "Asset Management",
      path: "/assetmanagement",
      subMenus: [
        {
          id: "vendor",
          label: "Vendor",
          path: "/assetmanagement/vendor",
          icon: <Store className="w-4 h-4" />,
        },
        {
          id: "location",
          label: "Location",
          path: "/assetmanagement/location",
          icon: <LocateIcon className="w-4 h-4" />,
        },
        {
          id: "assetCategory",
          label: "Asset Category",
          path: "/assetmanagement/assetcategory",
          icon: <Videotape className="w-4 h-4" />,
        },
        {
          id: "asset",
          label: "Asset",
          path: "/assetmanagement/asset",
          icon: <CassetteTape className="w-4 h-4" />,
        },
        {
          id: "assetassignment",
          label: "Asset Assignment",
          path: "/assetmanagement/assetassignment",
          icon: <Plug className="w-4 h-4" />,
        },
        {
          id: "purchase",
          label: "Purchase",
          path: "/assetmanagement/purchase",
          icon: <ShoppingCart className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "inventory",
      icon: <ShoppingBag className="w-5 h-5" />,
      label: "Inventory",
      path: "/inventory",
      subMenus: [
        {
          id: "category",
          label: "Category",
          path: "/inventory/category",
          icon: <ClipboardType className="w-4 h-4" />,
        },
        {
          id: "product",
          label: "Product",
          path: "/inventory/product",
          icon: <Speaker className="w-4 h-4" />,
        },
        {
          id: "warehouse",
          label: "Warehouse",
          path: "/inventory/warehouse",
          icon: <Warehouse className="w-4 h-4" />,
        },
        {
          id: "supplier",
          label: "Supplier",
          path: "/inventory/supplier",
          icon: <Container className="w-4 h-4" />,
        },
        {
          id: "purchase",
          label: "Purchase",
          path: "/inventory/purchase",
          icon: <ShoppingBasket className="w-4 h-4" />,
        },
        {
          id: "sale",
          label: "Sale",
          path: "/inventory/sale",
          icon: <BadgePoundSterling className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "leaveApplication",
      icon: <LetterText className="w-5 h-5" />,
      label: "Leave Application",
      path: "/leaveappication",
      subMenus: [
        {
          id: "leaveCategory",
          label: "Leave Category",
          path: "/leaveapplication/leavecategory",
          icon: <ChartCandlestick className="w-4 h-4" />,
        },
        {
          id: "leaveassign",
          label: "Leave Assign",
          path: "/leaveapplication/leaveassign",
          icon: <AudioLines className="w-4 h-4" />,
        },
        {
          id: "leaveApply",
          label: "Leave Apply",
          path: "/leaveapplication/leaveapply",
          icon: <FileUser className="w-4 h-4" />,
        },
        {
          id: "leaveapplications",
          label: "Leave Applications",
          path: "/leaveapplication/leaveapplications",
          icon: <MailQuestion className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "googleMeetClass",
      icon: <Presentation className="w-5 h-5" />,
      label: "Google Meet Class",
      path: "/googlemeetclass",
    },
    {
      id: "tutorial",
      icon: <Film className="w-5 h-5" />,
      label: "Tutorial",
      path: "/tutorial",
    },
    {
      id: "zoomMeeting",
      icon: <Fullscreen className="w-5 h-5" />,
      label: "Zoom Meeting",
      path: "/zoommeeting",
      subMenus: [
        {
          id: "liveclass",
          label: "Live Class",
          path: "/zoommeeting/liveclass",
          icon: <VideoIcon className="w-4 h-4" />,
        },
        {
          id: "zoomsettings",
          label: "Zoom Settings",
          path: "/zoommeeting/zoomsettings",
          icon: <Keyboard className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "child",
      icon: <Baby className="w-5 h-5" />,
      label: "Child",
      path: "/child",
      subMenus: [
        {
          id: "activitiescategory",
          label: "Activity Category",
          path: "/child/activitiescategory",
          icon: <Zap className="w-4 h-4" />,
        },
        {
          id: "activities",
          label: "Activiti",
          path: "/child/activities",
          icon: <Activity className="w-4 h-4" />,
        },
        {
          id: "childcare",
          label: "Child Care",
          path: "/child/childcare",
          icon: <Accessibility className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "library",
      icon: <Library className="w-5 h-5" />,
      label: "Library",
      path: "/library",
      subMenus: [
        {
          id: "member",
          label: "Member",
          path: "/library/member",
          icon: <User2Icon className="w-4 h-4" />,
        },
        {
          id: "books",
          label: "Books",
          path: "/library/books",
          icon: <BookOpenCheckIcon className="w-4 h-4" />,
        },
        {
          id: "issues",
          label: "Issues",
          path: "/library/issues",
          icon: <CarrotIcon className="w-4 h-4" />,
        },
        {
          id: "ebooks",
          label: "E-Books",
          path: "/library/ebooks",
          icon: <BookA className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "transport",
      icon: <Bus className="w-5 h-5" />,
      label: "Transport",
      path: "/transport",
      subMenus: [
        {
          id: "member",
          label: "Member",
          path: "/transport/member",
          icon: <User2Icon className="w-4 h-4" />,
        },
        {
          id: "transports",
          label: "Transports",
          path: "/transport/transports",
          icon: <BusFrontIcon className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "hotel",
      icon: <Hotel className="w-5 h-5" />,
      label: "Hotel",
      path: "/hotel",
      subMenus: [
        {
          id: "hostels",
          label: "Hostels",
          path: "/hostels/hostelslist",
          icon: <HousePlug className="w-4 h-4" />,
        },
        {
          id: "categories",
          label: "Categories",
          path: "/hostels/categories",
          icon: <Leaf className="w-4 h-4" />,
        },
        {
          id: "member",
          label: "Member",
          path: "/hostels/member",
          icon: <User2Icon className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "sponsorship",
      icon: <BadgeCent className="w-5 h-5" />,
      label: "Sponsorship",
      path: "/sponsorship",
      subMenus: [
        {
          id: "candidate",
          label: "Candidate",
          path: "/sponsorship/candidate",
          icon: <PersonStandingIcon className="w-4 h-4" />,
        },
        {
          id: "sponsors",
          label: "Sponsors",
          path: "/sponsorship/sponsors",
          icon: <PersonStanding className="w-4 h-4" />,
        },
        {
          id: "sponsorship",
          label: "sponsorship",
          path: "/sponsorship/sponsorships",
          icon: <MessageSquareCode className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "account",
      icon: <Inbox className="w-5 h-5" />,
      label: "Account",
      path: "/account",
      subMenus: [
        {
          id: "fee-types",
          label: "Fee Types",
          path: "/account/fee-types",
          icon: <ListChecks className="w-4 h-4" />,
        },
        {
          id: "invoice",
          label: "Invoice",
          path: "/account/invoice",
          icon: <Receipt className="w-4 h-4" />,
        },
        {
          id: "payment-history",
          label: "Payment History",
          path: "/account/payment-history",
          icon: <History className="w-4 h-4" />,
        },
        {
          id: "expense",
          label: "Expense",
          path: "/account/expense",
          icon: <TrendingDown className="w-4 h-4" />,
        },
        {
          id: "income",
          label: "Income",
          path: "/account/income",
          icon: <TrendingUp className="w-4 h-4" />,
        },
        {
          id: "global-payment",
          label: "Global Payment",
          path: "/account/global-payment",
          icon: <Globe className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "announcement",
      icon: <Volume className="w-5 h-5" />,
      label: "Announcement",
      path: "/announcement",
      subMenus: [
        {
          id: "notice",
          label: "Notice",
          path: "/announcement/notice",
          icon: <NotebookIcon className="w-4 h-4" />,
        },
        {
          id: "event",
          label: "Event",
          path: "/announcement/event",
          icon: <Projector className="w-4 h-4" />,
        },
        {
          id: "holiday",
          label: "Holiday",
          path: "/announcement/holiday",
          icon: <Umbrella className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "report",
      icon: <ClipboardMinus className="w-5 h-5" />,
      label: "Report",
      path: "/report",
      subMenus: [
        {
          id: "class-report",
          label: "Class Report",
          path: "/report/class",
          icon: <School className="w-4 h-4" />,
        },
        {
          id: "sponsorship-report",
          label: "Sponsorship Report",
          path: "/report/sponsorship",
          icon: <Users className="w-4 h-4" />,
        },
        {
          id: "student-report",
          label: "Student Report",
          path: "/report/student",
          icon: <UserSquare className="w-4 h-4" />,
        },
        {
          id: "id-card-report",
          label: "ID Card Report",
          path: "/report/id-card",
          icon: <IdCard className="w-4 h-4" />,
        },
        {
          id: "admit-card-report",
          label: "Admit Card Report",
          path: "/report/admit-card",
          icon: <Ticket className="w-4 h-4" />,
        },
        {
          id: "routing-report",
          label: "Routing Report",
          path: "/report/routing",
          icon: <Route className="w-4 h-4" />,
        },
        {
          id: "exam-schedule-report",
          label: "Exam Schedule Report",
          path: "/report/exam-schedule",
          icon: <CalendarClock className="w-4 h-4" />,
        },
        {
          id: "attendance-report",
          label: "Attendance Report",
          path: "/report/attendance",
          icon: <ClipboardCheck className="w-4 h-4" />,
        },
        {
          id: "attendance-overview-report",
          label: "Attendance Overview Report",
          path: "/report/attendance-overview",
          icon: <ClipboardList className="w-4 h-4" />,
        },
        {
          id: "library-books-report",
          label: "Library Books Report",
          path: "/report/library-books",
          icon: <BookOpen className="w-4 h-4" />,
        },
        {
          id: "library-card-report",
          label: "Library Card Report",
          path: "/report/library-card",
          icon: <Library className="w-4 h-4" />,
        },
        {
          id: "library-book-issue-report",
          label: "Library Book Issue Report",
          path: "/report/library-book-issue",
          icon: <BookCheck className="w-4 h-4" />,
        },
        {
          id: "terminal-report",
          label: "Terminal Report",
          path: "/report/terminal",
          icon: <Terminal className="w-4 h-4" />,
        },
        {
          id: "merit-stage-report",
          label: "Merit Stage Report",
          path: "/report/merit-stage",
          icon: <Award className="w-4 h-4" />,
        },
        {
          id: "tabulation-sheet-report",
          label: "Tabulation Sheet Report",
          path: "/report/tabulation-sheet",
          icon: <Table className="w-4 h-4" />,
        },
        {
          id: "mark-sheet-report",
          label: "Mark Sheet Report",
          path: "/report/mark-sheet",
          icon: <FileSpreadsheet className="w-4 h-4" />,
        },
        {
          id: "progress-report",
          label: "Progress Card Report",
          path: "/report/progress",
          icon: <TrendingUp className="w-4 h-4" />,
        },
        {
          id: "student-session-report",
          label: "Student Session Report",
          path: "/report/student-session",
          icon: <Clock1 className="w-4 h-4" />,
        },
        {
          id: "online-exam-report",
          label: "Online Exam Report",
          path: "/report/online-exam",
          icon: <MonitorPlay className="w-4 h-4" />,
        },
        {
          id: "online-exam-question-report",
          label: "Online Exam Question Report",
          path: "/report/online-exam-question",
          icon: <FileQuestion className="w-4 h-4" />,
        },
        {
          id: "online-exam-question-answer-report",
          label: "Online Exam Question Answer Report",
          path: "/report/online-exam-question-answer",
          icon: <FileCheck className="w-4 h-4" />,
        },
        {
          id: "online-admission-report",
          label: "Online Admission Report",
          path: "/report/online-admission",
          icon: <UserPlus className="w-4 h-4" />,
        },
        {
          id: "certificate-report",
          label: "Certificate Report",
          path: "/report/certificate",
          icon: <Award className="w-4 h-4" />,
        },
        {
          id: "leave-application-report",
          label: "Leave Application Report",
          path: "/report/leave-application",
          icon: <CalendarX className="w-4 h-4" />,
        },
        {
          id: "product-purchase-report",
          label: "Product Purchase Report",
          path: "/report/product-purchase",
          icon: <ShoppingCart className="w-4 h-4" />,
        },
        {
          id: "product-sale-report",
          label: "Product Sale Report",
          path: "/report/product-sale",
          icon: <ShoppingBag className="w-4 h-4" />,
        },
        {
          id: "search-payment-fees-report",
          label: "Search Payment Fees Report",
          path: "/report/search-payment-fees",
          icon: <Search className="w-4 h-4" />,
        },
        {
          id: "fees-report",
          label: "Fees Report",
          path: "/report/fees",
          icon: <Receipt className="w-4 h-4" />,
        },
        {
          id: "due-fees-report",
          label: "Due Fees Report",
          path: "/report/due-fees",
          icon: <AlertCircle className="w-4 h-4" />,
        },
        {
          id: "balance-fees-report",
          label: "Balance Fees Report",
          path: "/report/balance-fees",
          icon: <ScaleIcon className="w-4 h-4" />,
        },
        {
          id: "transaction-report",
          label: "Transaction Report",
          path: "/report/transaction",
          icon: <ArrowLeftRight className="w-4 h-4" />,
        },
        {
          id: "student-fine-report",
          label: "Student Fine Report",
          path: "/report/student-fine",
          icon: <AlertTriangle className="w-4 h-4" />,
        },
        {
          id: "overtime-report",
          label: "Overtime Report",
          path: "/report/overtime",
          icon: <Clock className="w-4 h-4" />,
        },
        {
          id: "salary-report",
          label: "Salary Report",
          path: "/report/salary",
          icon: <Wallet className="w-4 h-4" />,
        },
        {
          id: "account-ledger-report",
          label: "Account Ledger Report",
          path: "/report/account-ledger",
          icon: <BookText className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "onlineAdmission",
      icon: <EthernetPort className="w-5 h-5" />,
      label: "Online Admission",
      path: "/onlineadmission",
    },
    {
      id: "visitorInformation",
      icon: <PersonStanding className="w-5 h-5" />,
      label: "Visitor Information",
      path: "/visitorinformation",
    },
    {
      id: "administrator",
      icon: <LockIcon className="w-5 h-5" />,
      label: "Administrator",
      path: "/administrator",
      subMenus: [
        {
          id: "academic-year",
          label: "Academic Year",
          path: "/administrator/academic-year",
          icon: <Calendar className="w-4 h-4" />,
        },
        {
          id: "student-group",
          label: "Student Group",
          path: "/administrator/student-group",
          icon: <Users className="w-4 h-4" />,
        },
        {
          id: "complain",
          label: "Complain",
          path: "/administrator/complain",
          icon: <MessageCircle className="w-4 h-4" />,
        },
        {
          id: "certificate-template",
          label: "Certificate Template",
          path: "/administrator/certificate-template",
          icon: <FileText className="w-4 h-4" />,
        },
        {
          id: "system-admin",
          label: "System Admin",
          path: "/administrator/system-admin",
          icon: <Settings className="w-4 h-4" />,
        },
        {
          id: "reset-password",
          label: "Reset Password",
          path: "/administrator/reset-password",
          icon: <Key className="w-4 h-4" />,
        },
        {
          id: "social-link",
          label: "Social Link",
          path: "/administrator/social-link",
          icon: <Link className="w-4 h-4" />,
        },
        {
          id: "mail-sms-template",
          label: "Mail / SMS Template",
          path: "/administrator/mail-sms-template",
          icon: <Mail className="w-4 h-4" />,
        },
        {
          id: "import",
          label: "Import",
          path: "/administrator/import",
          icon: <Download className="w-4 h-4" />,
        },
        {
          id: "backup",
          label: "Backup",
          path: "/administrator/backup",
          icon: <Save className="w-4 h-4" />,
        },
        {
          id: "role",
          label: "Role",
          path: "/administrator/role",
          icon: <UserCog className="w-4 h-4" />,
        },
        {
          id: "permission",
          label: "Permission",
          path: "/administrator/permission",
          icon: <Shield className="w-4 h-4" />,
        },
        {
          id: "addons",
          label: "Addons",
          path: "/administrator/addons",
          icon: <PlusCircle className="w-4 h-4" />,
        },
        {
          id: "update",
          label: "Update",
          path: "/administrator/update",
          icon: <RefreshCw className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "frontend",
      icon: <House className="w-5 h-5" />,
      label: "Frontend",
      path: "/frontend",
      subMenus: [
        {
          id: "posts-categories",
          label: "Posts Categories",
          path: "/frontend/posts-categories",
          icon: <FolderTree className="w-4 h-4" />,
        },
        {
          id: "posts",
          label: "Posts",
          path: "/frontend/posts",
          icon: <FileText className="w-4 h-4" />,
        },
        {
          id: "pages",
          label: "Pages",
          path: "/frontend/pages",
          icon: <Files className="w-4 h-4" />,
        },
        {
          id: "menu",
          label: "Menu",
          path: "/frontend/menu",
          icon: <MenuSquare className="w-4 h-4" />,
        },
      ],
    },
    {
      id: "settings",
      icon: <Settings className="w-5 h-5" />,
      label: "Settings",
      path: "/settings",
      subMenus: [
        {
          id: "general-setting",
          label: "General Setting",
          path: "/settings/general",
          icon: <Settings2 className="w-4 h-4" />,
        },
        {
          id: "frontend-settings",
          label: "Frontend Settings",
          path: "/settings/frontend",
          icon: <LayoutTemplate className="w-4 h-4" />,
        },
        {
          id: "payment-settings",
          label: "Payment Settings",
          path: "/settings/payment",
          icon: <CreditCard className="w-4 h-4" />,
        },
        {
          id: "sms-settings",
          label: "SMS Settings",
          path: "/settings/sms",
          icon: <MessageSquare className="w-4 h-4" />,
        },
        {
          id: "email-setting",
          label: "Email Setting",
          path: "/settings/email",
          icon: <Mail className="w-4 h-4" />,
        },
        {
          id: "mark-setting",
          label: "Mark Setting",
          path: "/settings/mark",
          icon: <CheckSquare className="w-4 h-4" />,
        },
      ],
    },
  ];
};

export const menuItems = createMenuConfig();
